---
- name: Create systemd service
  template:
    src: petclinic.service.j2
    dest: /etc/systemd/system/petclinic.service
    mode: '0644'

- name: Reload service
  systemd:
    daemon_reload: yes

- name: Check the service
  shell: "systemctl status petclinic"
  register: system_result

- name: Display result
  debug:
    var: system_result

- name: Start the petclinic app
  systemd:
    name: petclinic
    enabled: yes
    state: started
    ignore_errors: yes

