---
- name: Create systemd service
  template:
    src: "{{ item }}.service.j2"
    dest: "{{ systemd_path }}/{{ item }}.service"
    mode: '0644'
  loop:
    - "{{ webapp }}"
    - "{{ exporter }}"
  when: "'webpetclinic' in group_names"

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: "'webpetclinic' in group_names"

- name: Start the services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "{{ webapp }}"
    - "{{ exporter }}"
  when: "'webpetclinic' in group_names"

- name: Create systemd service Prometheus
  template:
    src: "{{ item }}.service.j2"
    dest: "{{ systemd_path }}/{{ item }}.service"
    mode: '0644'
  loop:
    - "{{ monitoring }}"
  when: "'monitoring' in group_names"

- name: Add scraping target to prometheus.yml
  blockinfile:
    path: "/etc/{{ monitoring }}/{{ monitoring }}.yml"
    block: |
      - job_name: "node_exporter_petclinic"
      
        static_configs:
          - targets: ['10.0.0.5:9100']
    insertafter: EOF
    state: present
    backup: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: "'monitoring' in group_names"

- name: Start the services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "{{ monitoring }}"
  when: "'monitoring' in group_names"



