---
- name: Create systemd service
  template:
    src: petclinic.service.j2
    dest: /etc/systemd/system/petclinic.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start the petclinic app
  systemd:
    name: petclinic
    enabled: yes
    state: started

