---
- vars:
  services:
    - "{{ webapp }}"
    - "{{ exporter }}"

- name: Create systemd service
  template:
    src: "{{ item }}.service.j2"
    dest: "{{ systemd_path }}/{{ item }}.service"
    mode: '0644'
  loop: "{{ services }}"
  when: "'webpetclinic' in group_names"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start the services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ services }}"
  when: "'webpetclinic' in group_names"



