- name: Deploy .jar artifact
  copy:
    src: "/home/osansible/myagent/_work/1/s/target/spring-petclinic-3.5.0-SNAPSHOT.jar"
    dest: "/opt/petclinic/spring-petclinic-3.5.0-SNAPSHOT.jar"
    mode: '0755'