---
- name: Install java
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Application path
  file:
    path: "{{ application_path }}"
    state: directory
    mode: '0755'